export const xrayNames = [
  "Chest PA View",
  "Chest Lateral View",
  "Chest Bedside View",
  "Abdomen Supine",
  "Abdomen Upright",
  "Abdomen Lateral Decubitus",
  "Abdomen Cross-Table Lateral",
  "KUB X-Ray",
  "Cervical Spine AP",
  "Cervical Spine Lateral",
  "Cervical Spine Odontoid (Open-Mouth)",
  "Thoracic Spine AP",
  "Thoracic Spine Lateral",
  "Lumbar Spine AP",
  "Lumbar Spine Lateral",
  "Hip AP",
  "Hip Lateral",
  "Pelvis AP",
  "Pelvis Lateral",
  "Knee AP",
  "Knee Lateral",
  "Knee Sunrise (Axial)",
  "Knee Tunnel View",
  "Leg AP",
  "Leg Lateral",
  "Ankle AP",
  "Ankle Lateral",
  "Ankle Mortise View",
  "Foot AP",
  "Foot Lateral",
  "Foot Oblique",
  "Toes AP",
  "Toes Lateral",
  "Shoulder AP",
  "Shoulder Lateral",
  "Shoulder Axillary",
  "Elbow AP",
  "Elbow Lateral",
  "Forearm AP",
  "Forearm Lateral",
  "Wrist AP",
  "Wrist Lateral",
  "Wrist Oblique",
  "Hand AP",
  "Hand Lateral",
  "Hand Oblique",
  "Fingers AP",
  "Fingers Lateral"
];
